qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 46198 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 46473 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 46727 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 47049 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 47332 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 47529 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 47807 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 48057 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 48482 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 48744 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 48941 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 49136 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 49458 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 49691 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 50154 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 50369 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 50583 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 50875 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 51092 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 51403 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 51643 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
qt.qpa.xcb: could not connect to display :0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 51839 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
QObject::moveToThread: Current thread (0x564d666727d0) is not the object's thread (0x564d66610a80).
Cannot move to target thread (0x564d666727d0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/PyQt5/Qt5/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 52063 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
QObject::moveToThread: Current thread (0x55f901a237b0) is not the object's thread (0x55f9015c5650).
Cannot move to target thread (0x55f901a237b0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/PyQt5/Qt5/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 52320 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
QObject::moveToThread: Current thread (0x56202400e7b0) is not the object's thread (0x562023bb0650).
Cannot move to target thread (0x56202400e7b0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/ahmadfaisal/.local/lib/python3.9/site-packages/PyQt5/Qt5/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/run_test.sh: line 5: 52614 Aborted                 (core dumped) /usr/bin/python /home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py
Hello World: 1674101822.1915514
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Hello World: 1674101882.0091927
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
[ WARN:0@0.304] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@0.304] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
Hello World: 1674102093.837046
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Traceback (most recent call last):
  File "/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py", line 33, in <module>
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

[ WARN:0@0.284] global cap_v4l.cpp:982 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@0.284] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
Hello World: 1674102094.4593744
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Traceback (most recent call last):
  File "/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py", line 33, in <module>
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

[ WARN:0@0.457] global cap_v4l.cpp:969 open VIDEOIO(V4L2): can't find camera device
[ WARN:0@0.458] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.458] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ WARN:0@0.458] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.458] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ERROR:0@0.458] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
Hello World: 1674102782.1104102
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Traceback (most recent call last):
  File "/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py", line 33, in <module>
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674102841.586514
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674102902.2867956
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674102961.995621
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674103021.7219481
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Hello World: 1674103081.4454882
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674103142.1530569
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Hello World: 1674103201.8916397
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Hello World: 1674103261.6231222
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
[ WARN:0@0.386] global cap_v4l.cpp:969 open VIDEOIO(V4L2): can't find camera device
[ WARN:0@0.387] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.387] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ WARN:0@0.387] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.387] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ERROR:0@0.387] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
Hello World: 1674103682.1642356
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Traceback (most recent call last):
  File "/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py", line 33, in <module>
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

[ WARN:0@0.209] global cap_v4l.cpp:969 open VIDEOIO(V4L2): can't find camera device
[ WARN:0@0.209] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.209] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ WARN:0@0.209] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.209] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ERROR:0@0.209] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
Hello World: 1674103741.7698767
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Traceback (most recent call last):
  File "/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py", line 33, in <module>
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

[ WARN:0@0.206] global cap_v4l.cpp:969 open VIDEOIO(V4L2): can't find camera device
[ WARN:0@0.206] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.206] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ WARN:0@0.206] global obsensor_stream_channel_v4l2.cpp:82 xioctl ioctl: fd=-1, req=-2140645888
[ WARN:0@0.206] global obsensor_stream_channel_v4l2.cpp:138 queryUvcDeviceInfoList ioctl error return: 9
[ERROR:0@0.206] global obsensor_uvc_stream_channel.cpp:156 getStreamChannelGroup Camera index out of range
Hello World: 1674103802.3197086
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Traceback (most recent call last):
  File "/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py", line 33, in <module>
    frame_gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674103861.7868643
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674103921.49513
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
Hello World: 1674103982.1628187
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674104041.7626438
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674104101.4129684
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
Hello World: 1674104162.1336977
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana        Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
/home/ahmadfaisal/Documents/College/Semester_3/Tugas_Besar/Revisi_Digital_Image_Processing/face-recognition-based-attendance-system/face_recognition_based_attendance_system.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  attendance_df['attendance'].loc[attendance_df['full_name'] == most_common_name] = "Hadir"
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal  Tidak Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana  Tidak Hadir
          nim            full_name   attendance
0  1203210101  Ahmad Mu'min Faisal        Hadir
1  1203210068           Alif Rizky  Tidak Hadir
2  1203210030         Ivan Sholana        Hadir
